### ISSUE TITLE
Summary of meetings and to-do list

### ISSUE THREAD

**Issue by htwangtw** [htwangtw/heart-n-thoughts#3]
## From meeting
1. Clustering analysis of assessment data and use the cluster membership to revisit experience sampling data
    - [ ] PCA on assessment data
    - [ ] K-Mean clustering on Top PCs
    - [ ] Look up validation methods
2. Compile ECG data:
    - [ ] ~Session HRV~ pass to Joel
    - [ ] Go trials and probes HRV 10 seconds before the event
3. Pattern of missing trials in data

## My to-do
- [x] Add test and CI
- [ ] Refactor feature generation
